# Generated by Django 6.0.5 on 2026-05-18 06:59

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='blog')),
                ('title', models.CharField(max_length=150)),
                ('content', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('meta_title', models.CharField(blank=True, max_length=65, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=65, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='course')),
                ('name', models.CharField(max_length=150)),
                ('content', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('meta_title', models.CharField(blank=True, max_length=65, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=65, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='trainer')),
                ('name', models.CharField(max_length=150)),
                ('expert_in', models.CharField(max_length=200)),
            ],
        ),
    ]
