# Generated by Django 6.0.5 on 2026-05-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='meta_title',
        ),
    ]
